
package com.citybank.statementdtls.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.citybank.statementdtls.schema.req.StatementDtlsReqType;
import com.citybank.statementdtls.schema.res.StatementDtlsResType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StatementDetailsSvc", targetNamespace = "http://www.citybank.com/StatementDtls/service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.citybank.statementdtls.schema.req.ObjectFactory.class,
    com.citybank.statementdtls.schema.res.ObjectFactory.class
})
public interface StatementDetailsSvc {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.citybank.statementdtls.schema.res.StatementDtlsResType
     */
    @WebMethod
    @WebResult(name = "StatementDtlsRes", targetNamespace = "http://www.citybank.com/StatementDtls/schema/Res", partName = "parameters")
    public StatementDtlsResType getTransactions(
        @WebParam(name = "StatementDtlsReq", targetNamespace = "http://www.citybank.com/StatementDtls/schema/Req", partName = "parameters")
        StatementDtlsReqType parameters);

}
