
package org.nhs.patientinfo_srv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PatientInfo_Srv", targetNamespace = "http://www.nhs.org/PatientINfo_Srv/", wsdlLocation = "file:/D:/RTP3512/RTP3512/nhs/branches/Service/web/SOAP/PatientInfo_xsdwsdl/src/main/resources/PatientINfo_Srv.wsdl")
public class PatientInfoSrv_Service
    extends Service
{

    private final static URL PATIENTINFOSRV_WSDL_LOCATION;
    private final static WebServiceException PATIENTINFOSRV_EXCEPTION;
    private final static QName PATIENTINFOSRV_QNAME = new QName("http://www.nhs.org/PatientINfo_Srv/", "PatientInfo_Srv");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/RTP3512/RTP3512/nhs/branches/Service/web/SOAP/PatientInfo_xsdwsdl/src/main/resources/PatientINfo_Srv.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PATIENTINFOSRV_WSDL_LOCATION = url;
        PATIENTINFOSRV_EXCEPTION = e;
    }

    public PatientInfoSrv_Service() {
        super(__getWsdlLocation(), PATIENTINFOSRV_QNAME);
    }

    public PatientInfoSrv_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PATIENTINFOSRV_QNAME, features);
    }

    public PatientInfoSrv_Service(URL wsdlLocation) {
        super(wsdlLocation, PATIENTINFOSRV_QNAME);
    }

    public PatientInfoSrv_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PATIENTINFOSRV_QNAME, features);
    }

    public PatientInfoSrv_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PatientInfoSrv_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PatientInfoSrv
     */
    @WebEndpoint(name = "PatientINfo_Service_Port")
    public PatientInfoSrv getPatientINfoServicePort() {
        return super.getPort(new QName("http://www.nhs.org/PatientINfo_Srv/", "PatientINfo_Service_Port"), PatientInfoSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PatientInfoSrv
     */
    @WebEndpoint(name = "PatientINfo_Service_Port")
    public PatientInfoSrv getPatientINfoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.nhs.org/PatientINfo_Srv/", "PatientINfo_Service_Port"), PatientInfoSrv.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PATIENTINFOSRV_EXCEPTION!= null) {
            throw PATIENTINFOSRV_EXCEPTION;
        }
        return PATIENTINFOSRV_WSDL_LOCATION;
    }

}
