
package org.nhs.patientinfosrv.patientinfosrv.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import org.nhs.patientinfo.v1.schemas.req.PatientInfoReqType;
import org.nhs.patientinfo.v1.schemas.res.PatientInfoResType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PatientInfo_Srv", targetNamespace = "http://www.nhs.org/PatientINfo_Srv/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.nhs.patientinfo.v1.schemas.req.ObjectFactory.class,
    org.nhs.patientinfo.v1.schemas.res.ObjectFactory.class
})
public interface PatientInfoSrv {


    /**
     * 
     * @param parameters
     * @return
     *     returns org.nhs.patientinfo.v1.schemas.res.PatientInfoResType
     */
    @WebMethod(action = "http://www.example.org/PatientINfo_Srv/NewOperation")
    @WebResult(name = "PatientInfoRes", targetNamespace = "http://www.nhs.org/PatientInfo/v1/schemas/Res", partName = "parameters")
    @Action(input = "http://www.example.org/PatientINfo_Srv/NewOperation", output = "http://www.nhs.org/PatientINfo_Srv/PatientInfo_Srv/createPatientResponse")
    public PatientInfoResType createPatient(
        @WebParam(name = "PatientInfoReq", targetNamespace = "http://www.nhs.org/PatientInfo/v1/schemas/Req", partName = "parameters")
        PatientInfoReqType parameters);

}
