
package com.citybank.statementdtls.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StatementDetailsSvcImplService", targetNamespace = "http://impl.service.statementdtls.citybank.com/", wsdlLocation = "http://localhost:9005/StmtDetailsService-War/citybank?wsdl")
public class StatementDetailsSvcImplService
    extends Service
{

    private final static URL STATEMENTDETAILSSVCIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException STATEMENTDETAILSSVCIMPLSERVICE_EXCEPTION;
    private final static QName STATEMENTDETAILSSVCIMPLSERVICE_QNAME = new QName("http://impl.service.statementdtls.citybank.com/", "StatementDetailsSvcImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9005/StmtDetailsService-War/citybank?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STATEMENTDETAILSSVCIMPLSERVICE_WSDL_LOCATION = url;
        STATEMENTDETAILSSVCIMPLSERVICE_EXCEPTION = e;
    }

    public StatementDetailsSvcImplService() {
        super(__getWsdlLocation(), STATEMENTDETAILSSVCIMPLSERVICE_QNAME);
    }

    public StatementDetailsSvcImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STATEMENTDETAILSSVCIMPLSERVICE_QNAME, features);
    }

    public StatementDetailsSvcImplService(URL wsdlLocation) {
        super(wsdlLocation, STATEMENTDETAILSSVCIMPLSERVICE_QNAME);
    }

    public StatementDetailsSvcImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STATEMENTDETAILSSVCIMPLSERVICE_QNAME, features);
    }

    public StatementDetailsSvcImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StatementDetailsSvcImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StatementDetails
     */
    @WebEndpoint(name = "StatementDetailsSvcImplPort")
    public StatementDetails getStatementDetailsSvcImplPort() {
        return super.getPort(new QName("http://impl.service.statementdtls.citybank.com/", "StatementDetailsSvcImplPort"), StatementDetails.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StatementDetails
     */
    @WebEndpoint(name = "StatementDetailsSvcImplPort")
    public StatementDetails getStatementDetailsSvcImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.statementdtls.citybank.com/", "StatementDetailsSvcImplPort"), StatementDetails.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STATEMENTDETAILSSVCIMPLSERVICE_EXCEPTION!= null) {
            throw STATEMENTDETAILSSVCIMPLSERVICE_EXCEPTION;
        }
        return STATEMENTDETAILSSVCIMPLSERVICE_WSDL_LOCATION;
    }

}
