
package org.nhs.patientinfosrv.patientinfosrv.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PatientInfoSvcImplService", targetNamespace = "http://Impl.patientinfosrv.patientinfosrv.nhs.org/", wsdlLocation = "http://localhost:8888/PatientInfoSrv_war/PatientInfo?wsdl")
public class PatientInfoSvcImplService
    extends Service
{

    private final static URL PATIENTINFOSVCIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PATIENTINFOSVCIMPLSERVICE_EXCEPTION;
    private final static QName PATIENTINFOSVCIMPLSERVICE_QNAME = new QName("http://Impl.patientinfosrv.patientinfosrv.nhs.org/", "PatientInfoSvcImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/PatientInfoSrv_war/PatientInfo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PATIENTINFOSVCIMPLSERVICE_WSDL_LOCATION = url;
        PATIENTINFOSVCIMPLSERVICE_EXCEPTION = e;
    }

    public PatientInfoSvcImplService() {
        super(__getWsdlLocation(), PATIENTINFOSVCIMPLSERVICE_QNAME);
    }

    public PatientInfoSvcImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PATIENTINFOSVCIMPLSERVICE_QNAME, features);
    }

    public PatientInfoSvcImplService(URL wsdlLocation) {
        super(wsdlLocation, PATIENTINFOSVCIMPLSERVICE_QNAME);
    }

    public PatientInfoSvcImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PATIENTINFOSVCIMPLSERVICE_QNAME, features);
    }

    public PatientInfoSvcImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PatientInfoSvcImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PatientInfoSrv
     */
    @WebEndpoint(name = "PatientInfoSvcImplPort")
    public PatientInfoSrv getPatientInfoSvcImplPort() {
        return super.getPort(new QName("http://Impl.patientinfosrv.patientinfosrv.nhs.org/", "PatientInfoSvcImplPort"), PatientInfoSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PatientInfoSrv
     */
    @WebEndpoint(name = "PatientInfoSvcImplPort")
    public PatientInfoSrv getPatientInfoSvcImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Impl.patientinfosrv.patientinfosrv.nhs.org/", "PatientInfoSvcImplPort"), PatientInfoSrv.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PATIENTINFOSVCIMPLSERVICE_EXCEPTION!= null) {
            throw PATIENTINFOSVCIMPLSERVICE_EXCEPTION;
        }
        return PATIENTINFOSVCIMPLSERVICE_WSDL_LOCATION;
    }

}
