
package com.citybank.statementdetails.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.citybank.statementdtls_schema.req.StatementDtlsReqType;
import com.citybank.statementdtls_schema.resp.StatementDtlsResType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StatementDetails", targetNamespace = "http://www.citybank.com/StatementDetails/Service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.citybank.statementdtls_schema.req.ObjectFactory.class,
    com.citybank.statementdtls_schema.resp.ObjectFactory.class
})
public interface StatementDetails {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.citybank.statementdtls_schema.resp.StatementDtlsResType
     */
    @WebMethod(action = "http://www.citybank.com/StatementDetails/Service/NewOperation")
    @WebResult(name = "StatementDtlsRes", targetNamespace = "http://www.citybank.com/StatementDtls|Schema/Resp", partName = "parameters")
    public StatementDtlsResType getTrasactions(
        @WebParam(name = "StatementDtlsReq", targetNamespace = "http://www.citybank.com/StatementDtls|Schema/Req", partName = "parameters")
        StatementDtlsReqType parameters);

}
