//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.30 at 07:33:59 PM IST 
//


package com.citybank.statementdtls_schema.req;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StatementDtlsReqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StatementDtlsReqType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClientDetails" type="{http://www.citybank.com/StatementDtls|Schema/Req}ClientDetailsType"/>
 *         &lt;element name="CustomerDetails" type="{http://www.citybank.com/StatementDtls|Schema/Req}CustomerDetailsType"/>
 *         &lt;element name="TransCategory" type="{http://www.citybank.com/StatementDtls|Schema/Req}TransCategoryType"/>
 *         &lt;element name="ServiceDetails" type="{http://www.citybank.com/StatementDtls|Schema/Req}ServiceDetailsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatementDtlsReqType", propOrder = {
    "clientDetails",
    "customerDetails",
    "transCategory",
    "serviceDetails"
})
public class StatementDtlsReqType {

    @XmlElement(name = "ClientDetails", required = true)
    protected ClientDetailsType clientDetails;
    @XmlElement(name = "CustomerDetails", required = true)
    protected CustomerDetailsType customerDetails;
    @XmlElement(name = "TransCategory", required = true)
    protected TransCategoryType transCategory;
    @XmlElement(name = "ServiceDetails", required = true)
    protected ServiceDetailsType serviceDetails;

    /**
     * Gets the value of the clientDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ClientDetailsType }
     *     
     */
    public ClientDetailsType getClientDetails() {
        return clientDetails;
    }

    /**
     * Sets the value of the clientDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClientDetailsType }
     *     
     */
    public void setClientDetails(ClientDetailsType value) {
        this.clientDetails = value;
    }

    /**
     * Gets the value of the customerDetails property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerDetailsType }
     *     
     */
    public CustomerDetailsType getCustomerDetails() {
        return customerDetails;
    }

    /**
     * Sets the value of the customerDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerDetailsType }
     *     
     */
    public void setCustomerDetails(CustomerDetailsType value) {
        this.customerDetails = value;
    }

    /**
     * Gets the value of the transCategory property.
     * 
     * @return
     *     possible object is
     *     {@link TransCategoryType }
     *     
     */
    public TransCategoryType getTransCategory() {
        return transCategory;
    }

    /**
     * Sets the value of the transCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransCategoryType }
     *     
     */
    public void setTransCategory(TransCategoryType value) {
        this.transCategory = value;
    }

    /**
     * Gets the value of the serviceDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceDetailsType }
     *     
     */
    public ServiceDetailsType getServiceDetails() {
        return serviceDetails;
    }

    /**
     * Sets the value of the serviceDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceDetailsType }
     *     
     */
    public void setServiceDetails(ServiceDetailsType value) {
        this.serviceDetails = value;
    }

	@Override
	public String toString() {
		return "StatementDtlsReqType [clientDetails=" + clientDetails + ", customerDetails=" + customerDetails
				+ ", transCategory=" + transCategory + ", serviceDetails=" + serviceDetails + "]";
	}
    

}
