
package com.citybank.statementdtls.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StatementTransDetails", targetNamespace = "http://www.citybank.com/StatementDtls/service", wsdlLocation = "file:/D:/RTP23/StatementDtlsSvc-artifacts/src/main/resources/StatementDetailsService.wsdl")
public class StatementTransDetails
    extends Service
{

    private final static URL STATEMENTTRANSDETAILS_WSDL_LOCATION;
    private final static WebServiceException STATEMENTTRANSDETAILS_EXCEPTION;
    private final static QName STATEMENTTRANSDETAILS_QNAME = new QName("http://www.citybank.com/StatementDtls/service", "StatementTransDetails");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/RTP23/StatementDtlsSvc-artifacts/src/main/resources/StatementDetailsService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STATEMENTTRANSDETAILS_WSDL_LOCATION = url;
        STATEMENTTRANSDETAILS_EXCEPTION = e;
    }

    public StatementTransDetails() {
        super(__getWsdlLocation(), STATEMENTTRANSDETAILS_QNAME);
    }

    public StatementTransDetails(WebServiceFeature... features) {
        super(__getWsdlLocation(), STATEMENTTRANSDETAILS_QNAME, features);
    }

    public StatementTransDetails(URL wsdlLocation) {
        super(wsdlLocation, STATEMENTTRANSDETAILS_QNAME);
    }

    public StatementTransDetails(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STATEMENTTRANSDETAILS_QNAME, features);
    }

    public StatementTransDetails(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StatementTransDetails(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StatementDetailsService
     */
    @WebEndpoint(name = "StatementDetailsSOAP")
    public StatementDetailsService getStatementDetailsSOAP() {
        return super.getPort(new QName("http://www.citybank.com/StatementDtls/service", "StatementDetailsSOAP"), StatementDetailsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StatementDetailsService
     */
    @WebEndpoint(name = "StatementDetailsSOAP")
    public StatementDetailsService getStatementDetailsSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.citybank.com/StatementDtls/service", "StatementDetailsSOAP"), StatementDetailsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STATEMENTTRANSDETAILS_EXCEPTION!= null) {
            throw STATEMENTTRANSDETAILS_EXCEPTION;
        }
        return STATEMENTTRANSDETAILS_WSDL_LOCATION;
    }

}
