
package org.o2.registersvc.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RegisterServiceImplService", targetNamespace = "http://impl.service.registersvc.o2.org/", wsdlLocation = "http://localhost:8080/RegisterSvc_war/register?wsdl")
public class RegisterServiceImplService
    extends Service
{

    private final static URL REGISTERSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException REGISTERSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName REGISTERSERVICEIMPLSERVICE_QNAME = new QName("http://impl.service.registersvc.o2.org/", "RegisterServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/RegisterSvc_war/register?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REGISTERSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        REGISTERSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public RegisterServiceImplService() {
        super(__getWsdlLocation(), REGISTERSERVICEIMPLSERVICE_QNAME);
    }

    public RegisterServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REGISTERSERVICEIMPLSERVICE_QNAME, features);
    }

    public RegisterServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, REGISTERSERVICEIMPLSERVICE_QNAME);
    }

    public RegisterServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REGISTERSERVICEIMPLSERVICE_QNAME, features);
    }

    public RegisterServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegisterServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RegisterService
     */
    @WebEndpoint(name = "RegisterServiceImplPort")
    public RegisterService getRegisterServiceImplPort() {
        return super.getPort(new QName("http://impl.service.registersvc.o2.org/", "RegisterServiceImplPort"), RegisterService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegisterService
     */
    @WebEndpoint(name = "RegisterServiceImplPort")
    public RegisterService getRegisterServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.registersvc.o2.org/", "RegisterServiceImplPort"), RegisterService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REGISTERSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw REGISTERSERVICEIMPLSERVICE_EXCEPTION;
        }
        return REGISTERSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
