
package org.nhs.patientinfosvc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import org.nhs.patientinfo.v1.schemas.req.PatientInfoReqType;
import org.nhs.patientinfo.v1.schemas.resp.PatientInfoResType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PatientInfoSvc", targetNamespace = "http://www.nhs.org/PatientInfoSvc/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.nhs.patientinfo.v1.schemas.req.ObjectFactory.class,
    org.nhs.patientinfo.v1.schemas.resp.ObjectFactory.class
})
public interface PatientInfoSvc {


    /**
     * 
     * @param parameters
     * @return
     *     returns org.nhs.patientinfo.v1.schemas.resp.PatientInfoResType
     */
    @WebMethod(action = "http://www.example.org/PatientInfoSvc/NewOperation")
    @WebResult(name = "PatientInfoRes", targetNamespace = "http://www.nhs.org/PatientInfo/v1/schemas/Resp", partName = "parameters")
    public PatientInfoResType createPatient(
        @WebParam(name = "PatientInfoReq", targetNamespace = "http://www.nhs.org/PatientInfo/v1/schemas/Req", partName = "parameters")
        PatientInfoReqType parameters);

}
