//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.28 at 06:39:35 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sreenutech.org/OrdersReq", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.sreenutech.ordersreq;
