
package com.citybank.statementdtls.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StatementTransactionDetails", targetNamespace = "http://www.citybank.com/StatementDtls/service", wsdlLocation = "file:/D:/RTP3710/RTP3710/cstd/branches/services/soap/stmtdetailsSvc_artifacts/src/main/resources/StatementDetailsSvc.wsdl")
public class StatementTransactionDetails
    extends Service
{

    private final static URL STATEMENTTRANSACTIONDETAILS_WSDL_LOCATION;
    private final static WebServiceException STATEMENTTRANSACTIONDETAILS_EXCEPTION;
    private final static QName STATEMENTTRANSACTIONDETAILS_QNAME = new QName("http://www.citybank.com/StatementDtls/service", "StatementTransactionDetails");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/RTP3710/RTP3710/cstd/branches/services/soap/stmtdetailsSvc_artifacts/src/main/resources/StatementDetailsSvc.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STATEMENTTRANSACTIONDETAILS_WSDL_LOCATION = url;
        STATEMENTTRANSACTIONDETAILS_EXCEPTION = e;
    }

    public StatementTransactionDetails() {
        super(__getWsdlLocation(), STATEMENTTRANSACTIONDETAILS_QNAME);
    }

    public StatementTransactionDetails(WebServiceFeature... features) {
        super(__getWsdlLocation(), STATEMENTTRANSACTIONDETAILS_QNAME, features);
    }

    public StatementTransactionDetails(URL wsdlLocation) {
        super(wsdlLocation, STATEMENTTRANSACTIONDETAILS_QNAME);
    }

    public StatementTransactionDetails(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STATEMENTTRANSACTIONDETAILS_QNAME, features);
    }

    public StatementTransactionDetails(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StatementTransactionDetails(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StatementDetailsSvc
     */
    @WebEndpoint(name = "StatementDetailspost")
    public StatementDetailsSvc getStatementDetailspost() {
        return super.getPort(new QName("http://www.citybank.com/StatementDtls/service", "StatementDetailspost"), StatementDetailsSvc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StatementDetailsSvc
     */
    @WebEndpoint(name = "StatementDetailspost")
    public StatementDetailsSvc getStatementDetailspost(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.citybank.com/StatementDtls/service", "StatementDetailspost"), StatementDetailsSvc.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STATEMENTTRANSACTIONDETAILS_EXCEPTION!= null) {
            throw STATEMENTTRANSACTIONDETAILS_EXCEPTION;
        }
        return STATEMENTTRANSACTIONDETAILS_WSDL_LOCATION;
    }

}
