
package org.nhs.patientinfosvc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PatientInfoSvc", targetNamespace = "http://www.nhs.org/PatientInfoSvc/", wsdlLocation = "file:/D:/RTP3535/patientinfo_xsdndwsdl/src/main/resources/PatientInfoSvc.wsdl")
public class PatientInfoSvc_Service
    extends Service
{

    private final static URL PATIENTINFOSVC_WSDL_LOCATION;
    private final static WebServiceException PATIENTINFOSVC_EXCEPTION;
    private final static QName PATIENTINFOSVC_QNAME = new QName("http://www.nhs.org/PatientInfoSvc/", "PatientInfoSvc");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/RTP3535/patientinfo_xsdndwsdl/src/main/resources/PatientInfoSvc.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PATIENTINFOSVC_WSDL_LOCATION = url;
        PATIENTINFOSVC_EXCEPTION = e;
    }

    public PatientInfoSvc_Service() {
        super(__getWsdlLocation(), PATIENTINFOSVC_QNAME);
    }

    public PatientInfoSvc_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PATIENTINFOSVC_QNAME, features);
    }

    public PatientInfoSvc_Service(URL wsdlLocation) {
        super(wsdlLocation, PATIENTINFOSVC_QNAME);
    }

    public PatientInfoSvc_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PATIENTINFOSVC_QNAME, features);
    }

    public PatientInfoSvc_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PatientInfoSvc_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PatientInfoSvc
     */
    @WebEndpoint(name = "PatientInfoSvcPort")
    public PatientInfoSvc getPatientInfoSvcPort() {
        return super.getPort(new QName("http://www.nhs.org/PatientInfoSvc/", "PatientInfoSvcPort"), PatientInfoSvc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PatientInfoSvc
     */
    @WebEndpoint(name = "PatientInfoSvcPort")
    public PatientInfoSvc getPatientInfoSvcPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.nhs.org/PatientInfoSvc/", "PatientInfoSvcPort"), PatientInfoSvc.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PATIENTINFOSVC_EXCEPTION!= null) {
            throw PATIENTINFOSVC_EXCEPTION;
        }
        return PATIENTINFOSVC_WSDL_LOCATION;
    }

}
