
package com.citybank.statementdetails.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StatementDetailsService", targetNamespace = "http://www.citybank.com/StatementDetails/Service", wsdlLocation = "file:/D:/arunsunny/RTP3735/cstd/branches/service/soap/StmtDetailsSvc-artifacts/src/main/resources/StatementDetails.wsdl")
public class StatementDetailsService
    extends Service
{

    private final static URL STATEMENTDETAILSSERVICE_WSDL_LOCATION;
    private final static WebServiceException STATEMENTDETAILSSERVICE_EXCEPTION;
    private final static QName STATEMENTDETAILSSERVICE_QNAME = new QName("http://www.citybank.com/StatementDetails/Service", "StatementDetailsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/arunsunny/RTP3735/cstd/branches/service/soap/StmtDetailsSvc-artifacts/src/main/resources/StatementDetails.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STATEMENTDETAILSSERVICE_WSDL_LOCATION = url;
        STATEMENTDETAILSSERVICE_EXCEPTION = e;
    }

    public StatementDetailsService() {
        super(__getWsdlLocation(), STATEMENTDETAILSSERVICE_QNAME);
    }

    public StatementDetailsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STATEMENTDETAILSSERVICE_QNAME, features);
    }

    public StatementDetailsService(URL wsdlLocation) {
        super(wsdlLocation, STATEMENTDETAILSSERVICE_QNAME);
    }

    public StatementDetailsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STATEMENTDETAILSSERVICE_QNAME, features);
    }

    public StatementDetailsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StatementDetailsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StatementDetails
     */
    @WebEndpoint(name = "StatementDetailsSOAP")
    public StatementDetails getStatementDetailsSOAP() {
        return super.getPort(new QName("http://www.citybank.com/StatementDetails/Service", "StatementDetailsSOAP"), StatementDetails.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StatementDetails
     */
    @WebEndpoint(name = "StatementDetailsSOAP")
    public StatementDetails getStatementDetailsSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.citybank.com/StatementDetails/Service", "StatementDetailsSOAP"), StatementDetails.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STATEMENTDETAILSSERVICE_EXCEPTION!= null) {
            throw STATEMENTDETAILSSERVICE_EXCEPTION;
        }
        return STATEMENTDETAILSSERVICE_WSDL_LOCATION;
    }

}
